#! /bin/bash
# Copyright (c) 2017, Peter K. G. Williams.
#
# This file is part of Dedalus, which is free software distributed
# under the terms of the GPLv3 license.  A copy of the license should
# have been included in the file 'LICENSE.txt', and is also available
# online at <http://www.gnu.org/licenses/gpl-3.0.html>.

function die () {
    echo >&2 "error:" "$@"
    exit 1
}

stack=$(cd $(dirname $0) && pwd)/stack

if [ ! -f $stack/.setup-complete ] ; then
    die "software stack not yet set up; please run ./initialize first"
fi

prefix="$1"
shift

if [ -z "$prefix" ] ; then
    prefix=$(dirname $(dirname $(which conda)))
    echo "Installing into the Anaconda installation at \"$prefix\"."
    echo "Hit \"n\" below if that is not what you want."
fi

"$prefix"/bin/conda install --override-channels -c file://$stack/conda-bld -c conda-forge dedalus
